Biome ID changes
bedrock-viz/bedrock-viz pull request #184
Opened 2023-07-18 15:55 UTC by zimage

I changed biome ids to match what's in the wiki and in my 1.20 world and removed biomes from the legend that don't exist but were previously mapped to a biome id that is legitimate.

2023-07-19 03:46 UTC, zimage commented
My branch has been synced with bedrock-viz:master and is ready to be merged if all looks well.

2023-07-19 11:52 UTC, geoffholden requested changes

2023-07-19 11:52 UTC, geoffholden commented on static/bedrock_viz_legend.html
> -</div>
Dripstone Caves still exists in `bedrock_viz.xml`

2023-07-19 16:12 UTC, zimage commented on static/bedrock_viz_legend.html
> -</div>
Oops. Accidentally dropped that when reconciling with the other biome-related pull request. Fixed now.

2023-07-21 21:46 UTC, zimage reviewed
I've added Dripstone caves back.

2023-07-21 23:30 UTC, merged