Issue #40 - Limit rendering into specified X/Z chunk coordinates
bedrock-viz/bedrock-viz pull request #91
Opened 2021-01-02 16:37 UTC by wgebczyk

Hey!

Here is small HACK to allow limit map region. It is attempt to implement enhancement #40 .
I've tried to mimic existing code style, even if is inconsistent.

Feel free to reject that if not needed.

Checked on Windows only, seems to work as expected.

2021-01-10 21:12 UTC, wgebczyk commented
Are you interested in this proposal? If no, I would remove my forked repo.

Thanks!

2021-01-23 01:01 UTC, cmbkla commented
> Are you interested in this proposal? If no, I would remove my forked repo.
> 
> Thanks!

I wish you hadn't closed this. It does seem like things have kind of stalled here, but I'm also too used to sprint work. This is volunteer, it won't have fast timelines.

That said, it is kind of demoralizing when OS projects don't respond at all to PRs for a while. You never know if it's just a blip while folks are busy, or the beginning of radio silence -- like what happened to the repo this got forked from.

IDK man. I suggest renewing this PR and just waiting a bit. To the maintainers, I suggest a little more responsiveness, even a comment that says, "thanks man, really busy right now but I'll circle back asap!"

2021-01-23 16:12 UTC, counterfitninja commented
I think this is great idea. People who make this are doing it in the free time and it will eb and flow. its lucky we have the nether update on it. I would leave the issue open and see if people pick it up.

2021-01-25 20:29 UTC, wgebczyk commented
Hey!

Sorry to not respond faster. A few comments:

* The change is simple, a bit hackish to my taste but just works
* The release period of this tool/app is so slow, that I'm OK to keep proposed changes and just merge them manually after each release - so I don't feel urge to push for merge
* The automated builds fails, but from logs it seems not too much related to my changes (Run microsoft/setup-msbuild@v1.0.0 Failed) - hence I do not know if my changes are OK, or works by accident
* Changes are small, then even if I drop my PR/branch, anyone can pick up modifications and apply if needed in future months if they are OK

RE-opened as suggested. Will keep my fork longer, instead of local patch I was using before.
Still I hope someone will review that, as I do not see any effort to implement that rather crucial functionality as soon as you will get 4000+ discovered "pixels"

2021-01-28 00:51 UTC, cmbkla commented
Thanks for re-opening! I'll make a deal, if this thing dies, I'll start a new fork and be more active on the reviews on iteration #3. You be my go-to C++ guy because I have no idea about this backend :p

2021-02-16 16:50 UTC, counterfitninja commented
@wgebczyk any chance you can post you .exe with the limits in it? i have a map that someone flew 30k blocks away and now the maps always renders in the wrong place. I really like this project and hope people can keep it moving forward/

2021-06-30 04:00 UTC, cabbey requested changes
Thank you for taking a crack at this change... it feels super useful, and after playing with it for a short period I want to include it! But as you noted in your description, it feels a little hacky... dimensions are an important part of the game, so they need to be factored in; and there's some unrelated changes mixed in here that I'm not comfortable with. If you want to try to polish this up a little, please start a fresh branch with just the topical change (first commit) and work from there. (Or if you already have one, let's get a fresh PR based on that branch rather than your master branch. If you need some help with the git machinations, feel free to ask on discord, there's a number of folks there I suspect can help with them.)

2021-07-06 19:48 UTC, wgebczyk commented on src/main.cc
> +					// good
Yup! You are right. This could be handled during initial processing of input parameters - this normalization.

2021-07-06 19:59 UTC, wgebczyk commented on src/world/world.cc
> +            dimDataList[i]->unsetChunkBoundsValid(control.limitXMin, control.limitZMin);
Yes, current implementation is kind of shortcut.

Let's talk a bit before making any new branch/PR.

As I understand the code, you are trying to calculate bounding rectangle from generated world. You are processing one by one all chunks/blocks and expand this rectangle. To make it work, you either need to initialize rectangle to some "empty" value OR initialize with single point (rect size 1) that is guaranteed to be inside of final rectangle. Current implementation makes an assumption that (0,0) will be always in generated world chunks. In general there is small number of generated worlds that this might be not true and... generated images will be artificially extended to include (0,0). This could be handled in multiple ways:
- have sentinel value of meaning NOT_SET and make IF statements when expanding area to additionally check if coordinate is NOT_SET
- have additional flag that indicates NOT_SET and handle that on each rectangle expansion
- initialize with point that is guaranteed to be inside of final rectangle world.

The benefit of 3rd option is that you do not have to make additional check on EACH processed chunk/block. How much there is this additional work? I do not know.

BTW: Even with my changes, the issue with 0,0 is still there. Probably to make it work the code should:
- check if user wants to limit bounds, if so, choose any point inside of user defined rect bounds
- otherwise delay initialization till reading first chunk/block and then use it's coords as initialization point

BTW2: There is still small corner case where eg the world is [0;0 - 100;100] and user want bounds [-50;-50 - 50;50], should the final bounds be exactly as user expressed where 3 quarters are empty OR final bounds should be intersection of world bounds and user entered bounds (with possibility of empty set

2021-07-06 20:05 UTC, wgebczyk commented on src/main.cc
> +			("limit-z", value<std::string>(), "Min,max of Z chunk coordinates")
Do you want to allow multiple limit parameters? Like:
`--limit-x 0,10,100 --limit-x 1,20,40 --limit-x 2,100,101` to cut independently each dimension?

Do you want to align this parameters with `--movie-dim x,y,w,h`?

Unfortunately it is hard to reverse engineer what is preferred/standard way looking at existing command line arguments.

2021-07-06 20:05 UTC, wgebczyk commented on .github/workflows/pipeline.yml
> +      uses: microsoft/setup-msbuild@v1.0.2
I will remove. Please fix pipeline separately as it is very confusing when your PR breaks for unrelated reason.

2021-07-06 20:07 UTC, wgebczyk commented
As soon we clarify all questions and envisioned shape of this change, I will be happy to drop this PR and start new one from scratch. The changes are small and I hope master didn't change too much and I will be able to find appropriate places to plug in my changes.

Thanks!

2021-07-07 05:30 UTC, cabbey commented on .github/workflows/pipeline.yml
> +      uses: microsoft/setup-msbuild@v1.0.2
The windows pipeline is already fixed in the main codebase. There's a recurring issue with the reporting ci I've asked those that can do something with to do so.

2021-07-07 05:32 UTC, cabbey commented on src/main.cc
> +			("limit-z", value<std::string>(), "Min,max of Z chunk coordinates")
We do need to support multiple calls with different dimensions, yes. I think the example you gave is the one we'll want to follow. `--movie-dim` is not related to the game world dimensions, and is instead a video file dimension... so it's not a good pattern to follow in this case.

2021-07-07 05:49 UTC, cabbey commented on src/world/world.cc
> +            dimDataList[i]->unsetChunkBoundsValid(control.limitXMin, control.limitZMin);
> As I understand the code, you are trying to calculate bounding rectangle from generated world. You are processing one by one all chunks/blocks and expand this rectangle. To make it work, you either need to initialize rectangle to some "empty" value OR initialize with single point (rect size 1) that is guaranteed to be inside of final rectangle. Current implementation makes an assumption that (0,0) will be always in generated world chunks.

This is inline with my understanding of the code as well.

> In general there is small number of generated worlds that this might be not true and... generated images will be artificially extended to include (0,0). This could be handled in multiple ways:

Yes, this is quite common with the Nether.

>     * have sentinel value of meaning NOT_SET and make IF statements when expanding area to additionally check if coordinate is NOT_SET
> 
>     * have additional flag that indicates NOT_SET and handle that on each rectangle expansion

I think this is a singe boolean (per dimension, just as these min/max x/z values are... and the limits need to be) that is set on the very first chunk processed. At that point we will have min/max x/z values of the four edges of that chunk so we can initialize them and flip that boolean, after that it's the normal code as it exists today. There's a similar issue needed for Y values as well... we need to capture the min/max Y value that we encounter from the db as we are parsing the chunks. Today it really only matters for the Nether, but in the very near future it will matter for the overworld as well... since 1.18 is known to be changing that.

>     * initialize with point that is guaranteed to be inside of final rectangle world.
> 
> 
> The benefit of 3rd option is that you do not have to make additional check on EACH processed chunk/block. How much there is this additional work? I do not know.

it should be pretty minimal, the compiler will turn that into a very short path.

> BTW: Even with my changes, the issue with 0,0 is still there. Probably to make it work the code should:
> 
>     * check if user wants to limit bounds, if so, choose any point inside of user defined rect bounds
> 
>     * otherwise delay initialization till reading first chunk/block and then use it's coords as initialization point

Yes, I think this is the route we should take in all cases, so that the logic inside the min/max x/z detection doesn't need to be aware of the limits, it can just act on the chunks that are sent to it, which your limit code will control.

> BTW2: There is still small corner case where eg the world is [0;0 - 100;100] and user want bounds [-50;-50 - 50;50], should the final bounds be exactly as user expressed where 3 quarters are empty OR final bounds should be intersection of world bounds and user entered bounds (with possibility of empty set

This is a VERY good point. I think the goal should be to render the area in common between the two sets. So the `--limit-*` values do not set the edges of the map, they only set the limits of the blocks that will be included out of what is found in the db. I'm positive that the vast majority of users of these switches will only use it to subset an otherwise too large map... but we should not intentionally limit our thinking to that use case.

2021-07-07 05:57 UTC, cabbey commented
@wgebczyk you shouldn't need to start from scratch. I don't know how familiar you are with git, but I would expect a workflow like this would allow you to leverage much of the work done here, while creating a clean feature branch that doesn't have any of the unrelated changes:

```
# obtain changes from upstream
git fetch upstream
# switch the working directory to the current upstream master
git checkout upstream/master
# remove the current "master" branch that has changes in it
git branch -D master
# create a clean master branch from upstream
git branch master
# and switch to it
git checkout master
# make a new branch to work in
git checkout limit-xz
# then recover most of the work from before
git chery-pick 2e70ad76a0fb2c3bf0184e52c2e5f821332c6631
```

as of right now, the head of master will allow that commit to cherry-pick cleanly, no conflicts at all.

2021-08-08 16:42 UTC, kezzico commented
No problem building on Ubuntu 20.04

This error comes up though:

$ ./bedrock-viz --db ~/worlds/Kamanaka --limit-z 0,1,0 --limit-x 0,1,0
```
terminate called after throwing an instance of 'boost::wrapexcept<boost::bad_any_cast>'
  what():  boost::bad_any_cast: failed conversion using boost::any_cast
Aborted (core dumped)
```

2021-09-05 18:36 UTC, closed without merging